/* eslint-disable */
const fs = require('fs');
const path = require('path');
const { version } = require('../package.json');

const outPath = path.join(__dirname, '../src/version.ts');
const contents = `// Generated by tools/generate-version.js — do not edit.
export const VERSION = '${version}'; // x-release-please-version
`;

fs.writeFileSync(outPath, contents);
console.log(`Generated ${outPath} with VERSION=${version}`);
