name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-please:
    name: Run release-please
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - id: get-github-app-token
        uses: grafana/shared-workflows/actions/create-github-app-token@580590a644e82e79bb2598bdaba0be245a14dda0 # create-github-app-token/v0.2.2
        with:
          github_app: pyroscope-development-app

      - id: rp
        uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5
        with:
          token: ${{ steps.get-github-app-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
