name: Test

on:
  push:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'
    branches:
      - main
      - master
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'
      - '.editorconfig'
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-x64-small
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: 'false'
      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 26.x
          package-manager-cache: false
      - name: Enable corepack
        run: corepack enable
      - name: Install modules
        run: yarn
      - name: Check version.ts is in sync with package.json
        run: yarn check:version
      - name: Lint code base
        run: yarn lint
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-x64-small
        node: [20.x, 22.x, 24.x, 26.x]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: 'false'
      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: ${{ matrix.node }}
          package-manager-cache: false
      - name: Enable corepack
        run: corepack enable
      - name: Install modules
        run: yarn
      - name: Run build
        run: yarn build
      - name: Run tests
        run: yarn test
